/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihanKu;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ASUS
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        buttonDashboard = new javax.swing.JButton();
        buttonJurusan = new javax.swing.JButton();
        buttonGuru = new javax.swing.JButton();
        buttonKelas = new javax.swing.JButton();
        buttonSiswa = new javax.swing.JButton();
        buttonAbout = new javax.swing.JButton();
        buttonClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainFramePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        sidebarPanel.setBackground(new java.awt.Color(0, 153, 255));

        buttonDashboard.setBackground(new java.awt.Color(0, 153, 255));
        buttonDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonDashboard.setForeground(new java.awt.Color(255, 255, 255));
        buttonDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-dashboard2-24.png"))); // NOI18N
        buttonDashboard.setText("DASHBOARD");
        buttonDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        buttonDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDashboard.setIconTextGap(10);
        buttonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDashboardActionPerformed(evt);
            }
        });

        buttonJurusan.setBackground(new java.awt.Color(0, 153, 255));
        buttonJurusan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonJurusan.setForeground(new java.awt.Color(255, 255, 255));
        buttonJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-school-building-24.png"))); // NOI18N
        buttonJurusan.setText("JURUSAN");
        buttonJurusan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        buttonJurusan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonJurusan.setIconTextGap(10);
        buttonJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJurusanActionPerformed(evt);
            }
        });

        buttonGuru.setBackground(new java.awt.Color(0, 153, 255));
        buttonGuru.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonGuru.setForeground(new java.awt.Color(255, 255, 255));
        buttonGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-teacher-24.png"))); // NOI18N
        buttonGuru.setText("GURU");
        buttonGuru.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        buttonGuru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonGuru.setIconTextGap(10);
        buttonGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuruActionPerformed(evt);
            }
        });

        buttonKelas.setBackground(new java.awt.Color(0, 153, 255));
        buttonKelas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKelas.setForeground(new java.awt.Color(255, 255, 255));
        buttonKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-class-24.png"))); // NOI18N
        buttonKelas.setText("KELAS");
        buttonKelas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        buttonKelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonKelas.setIconTextGap(10);
        buttonKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKelasActionPerformed(evt);
            }
        });

        buttonSiswa.setBackground(new java.awt.Color(0, 153, 255));
        buttonSiswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonSiswa.setForeground(new java.awt.Color(255, 255, 255));
        buttonSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-person-24.png"))); // NOI18N
        buttonSiswa.setText("SISWA");
        buttonSiswa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        buttonSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonSiswa.setIconTextGap(10);
        buttonSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSiswaActionPerformed(evt);
            }
        });

        buttonAbout.setBackground(new java.awt.Color(0, 153, 255));
        buttonAbout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonAbout.setForeground(new java.awt.Color(255, 255, 255));
        buttonAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-about-24.png"))); // NOI18N
        buttonAbout.setText("ABOUT");
        buttonAbout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        buttonAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonAbout.setIconTextGap(10);
        buttonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAboutActionPerformed(evt);
            }
        });

        buttonClose.setBackground(new java.awt.Color(0, 153, 255));
        buttonClose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonClose.setForeground(new java.awt.Color(255, 255, 255));
        buttonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-logout-24.png"))); // NOI18N
        buttonClose.setText("LOGOUT");
        buttonClose.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        buttonClose.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonClose.setIconTextGap(10);
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-graduation-32.png"))); // NOI18N
        jLabel1.setText("Alumni");

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
            .addComponent(buttonJurusan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(buttonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
        );

        mainFramePanel.setBackground(new java.awt.Color(204, 204, 204));
        mainFramePanel.setLayout(new java.awt.CardLayout(1, 1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-close2-20.png"))); // NOI18N
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainFramePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainFramePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDashboardActionPerformed
        // TODO add your handling code here:
        mainFramePanel.removeAll();
        mainFramePanel.add(new dashboardPanel());
        mainFramePanel.revalidate();
        mainFramePanel.repaint();
    }//GEN-LAST:event_buttonDashboardActionPerformed

    private void buttonJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJurusanActionPerformed
        // TODO add your handling code here:
        mainFramePanel.removeAll();
        mainFramePanel.add(new jurusanPanel());
        mainFramePanel.revalidate();
        mainFramePanel.repaint();
    }//GEN-LAST:event_buttonJurusanActionPerformed

    private void buttonGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuruActionPerformed
        // TODO add your handling code here:
        mainFramePanel.removeAll();
        mainFramePanel.add(new dataGuruPanel());
        mainFramePanel.revalidate();
        mainFramePanel.repaint();
    }//GEN-LAST:event_buttonGuruActionPerformed

    private void buttonKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKelasActionPerformed
        // TODO add your handling code here:
        mainFramePanel.removeAll();
        mainFramePanel.add(new kelasPanel());
        mainFramePanel.revalidate();
        mainFramePanel.repaint();
    }//GEN-LAST:event_buttonKelasActionPerformed

    private void buttonSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSiswaActionPerformed
        // TODO add your handling code here:
        mainFramePanel.removeAll();
        mainFramePanel.add(new siswaPanel());
        mainFramePanel.revalidate();
        mainFramePanel.repaint();
    }//GEN-LAST:event_buttonSiswaActionPerformed

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        // TODO add your handling code here:
        int yesNo = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (yesNo == JOptionPane.YES_OPTION) {
        dispose();
        new loginFrame().setVisible(true);
            
        }              
    }//GEN-LAST:event_buttonCloseActionPerformed

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        int yesNo = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (yesNo == JOptionPane.YES_OPTION) {
        dispose();
        new loginFrame().setVisible(true);
            
        }
    }//GEN-LAST:event_closeLabelMouseClicked

    private void buttonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAboutActionPerformed
        // TODO add your handling code here:
         mainFramePanel.removeAll();
        mainFramePanel.add(new aboutPanel());
        mainFramePanel.revalidate();
        mainFramePanel.repaint();
    }//GEN-LAST:event_buttonAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbout;
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonDashboard;
    private javax.swing.JButton buttonGuru;
    private javax.swing.JButton buttonJurusan;
    private javax.swing.JButton buttonKelas;
    private javax.swing.JButton buttonSiswa;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainFramePanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
